import type { CustomEntitySpec, CustomFieldDefinition } from '@open-mercato/shared/modules/entities'

const clientConnectionFields = [
  {
    key: 'client_profile_id',
    kind: 'text',
    label: 'Client Profile ID',
    required: true,
    indexed: true,
    filterable: true,
    formEditable: false,
  },
  {
    key: 'tool',
    kind: 'select',
    label: 'Tool',
    options: ['ga4', 'meta_ads', 'google_ads', 'gtm', 'slack', 'email'],
    required: true,
    indexed: true,
    filterable: true,
    formEditable: true,
  },
  {
    key: 'external_id',
    kind: 'text',
    label: 'External ID / Webhook URL',
    description: 'GA4 Property ID, Meta Ads Account ID, Slack Webhook URL, etc. Encrypted at rest.',
    formEditable: true,
  },
  {
    key: 'display_name',
    kind: 'text',
    label: 'Display Name',
    description: 'e.g. "GA4 — produkcja", "Meta Ads — konto główne"',
    formEditable: true,
  },
  {
    key: 'status',
    kind: 'select',
    label: 'Status',
    options: ['connected', 'disconnected', 'error'],
    defaultValue: 'disconnected',
    indexed: true,
    filterable: true,
    formEditable: true,
  },
  {
    key: 'last_synced_at',
    kind: 'text',
    label: 'Last Synced At',
    description: 'ISO 8601 timestamp',
    indexed: true,
    formEditable: false,
  },
  {
    key: 'account_name',
    kind: 'text',
    label: 'Account Name',
    description: 'Verified account name from the ad platform',
    formEditable: false,
  },
  {
    key: 'account_currency',
    kind: 'text',
    label: 'Account Currency',
    description: 'Account currency code (e.g., PLN, USD)',
    formEditable: false,
  },
  {
    key: 'verified_at',
    kind: 'text',
    label: 'Verified At',
    description: 'ISO 8601 timestamp of last successful verification',
    formEditable: false,
  },
  {
    key: 'error_message',
    kind: 'text',
    label: 'Error Message',
    description: 'Last error message from verification or sync',
    formEditable: false,
  },
  {
    key: 'cached_campaigns',
    kind: 'multiline',
    label: 'Cached Campaigns',
    description: 'JSON array of campaign summaries from last sync',
    formEditable: false,
  },
  {
    key: 'cached_metrics',
    kind: 'multiline',
    label: 'Cached Metrics',
    description: 'JSON object with recent performance metrics from last sync',
    formEditable: false,
  },
  {
    key: 'campaigns_count',
    kind: 'text',
    label: 'Campaigns Count',
    description: 'Number of campaigns in the account',
    formEditable: false,
  },
] satisfies CustomFieldDefinition[]

const agentActionFields = [
  {
    key: 'client_profile_id',
    kind: 'text',
    label: 'Client Profile ID',
    required: true,
    indexed: true,
    filterable: true,
    formEditable: false,
  },
  {
    key: 'agent_type',
    kind: 'select',
    label: 'Agent Type',
    options: ['optimizer', 'analyst', 'content_creator', 'media_buyer'],
    indexed: true,
    filterable: true,
    formEditable: true,
  },
  {
    key: 'action_type',
    kind: 'select',
    label: 'Action Type',
    options: [
      'bid_adjustment',
      'budget_reallocation',
      'audience_update',
      'creative_test',
      'pause_campaign',
      'campaign_create',
      'report',
      'alert',
    ],
    indexed: true,
    filterable: true,
    formEditable: true,
  },
  {
    key: 'title',
    kind: 'text',
    label: 'Title',
    required: true,
    indexed: true,
    formEditable: true,
  },
  {
    key: 'rationale',
    kind: 'multiline',
    label: 'Rationale',
    editor: 'markdown',
    description: 'Why the agent made this decision',
    formEditable: true,
  },
  {
    key: 'status',
    kind: 'select',
    label: 'Status',
    options: ['proposed', 'approved', 'executing', 'done', 'failed', 'skipped'],
    defaultValue: 'proposed',
    indexed: true,
    filterable: true,
    formEditable: true,
  },
  {
    key: 'impact_estimate',
    kind: 'text',
    label: 'Impact Estimate',
    description: 'Expected outcome, e.g. "ROAS +8%, CPC -15%"',
    formEditable: true,
  },
  {
    key: 'result',
    kind: 'multiline',
    label: 'Result',
    editor: 'markdown',
    description: 'What actually happened after execution',
    formEditable: true,
  },
  {
    key: 'connection_id',
    kind: 'text',
    label: 'Connection ID',
    description: 'Which client_connection this action targets',
    indexed: true,
    formEditable: false,
  },
] satisfies CustomFieldDefinition[]

const campaignPlanFields = [
  {
    key: 'client_profile_id',
    kind: 'text',
    label: 'Client Profile ID',
    required: true,
    indexed: true,
    filterable: true,
    formEditable: false,
  },
  {
    key: 'status',
    kind: 'select',
    label: 'Status',
    options: ['draft', 'generating', 'ready', 'failed'],
    defaultValue: 'draft',
    indexed: true,
    filterable: true,
    formEditable: false,
  },
  {
    key: 'channel_breakdown',
    kind: 'multiline',
    label: 'Channel Breakdown & Budget',
    editor: 'markdown',
    description: 'Per-channel budget allocation and strategy',
    formEditable: true,
  },
  {
    key: 'creative_briefs',
    kind: 'multiline',
    label: 'Creative Briefs',
    editor: 'markdown',
    description: 'Creative direction per channel',
    formEditable: true,
  },
  {
    key: 'funnel_stages',
    kind: 'multiline',
    label: 'Funnel Stages',
    editor: 'markdown',
    description: 'Awareness → Consideration → Conversion stages',
    formEditable: true,
  },
  {
    key: 'kpis',
    kind: 'multiline',
    label: 'KPIs & Goals',
    editor: 'markdown',
    description: 'Key performance indicators and measurement plan',
    formEditable: true,
  },
  {
    key: 'generated_at',
    kind: 'text',
    label: 'Generated At',
    description: 'ISO 8601 timestamp',
    indexed: true,
    formEditable: false,
  },
] satisfies CustomFieldDefinition[]

export const entities: CustomEntitySpec[] = [
  {
    id: 'agency_intelligence:client_connection',
    label: 'Client Connection',
    description: 'Links a client profile to an external marketing tool (GA4, Meta Ads, Slack, etc.).',
    showInSidebar: false,
    fields: clientConnectionFields,
  },
  {
    id: 'agency_intelligence:agent_action',
    label: 'Agent Action',
    description: 'Log entry of an AI agent decision or action for a client.',
    showInSidebar: false,
    fields: agentActionFields,
  },
  {
    id: 'agency_intelligence:campaign_plan',
    label: 'Campaign Plan',
    description: 'AI-generated performance marketing campaign plan for a client.',
    showInSidebar: false,
    fields: campaignPlanFields,
  },
]

export default entities
